---
abstract: 'emulate rolling dice'
author:
  - 'Peter L. Berghold <peter@berghold.net>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPG-Dice
requires:
  Carp: 0
  strict: 0
  warnings: 0
version: 1.1
